### ISSUE TITLE
Typo in reverse iteration

### ISSUE THREAD

**Issue by velocityzen** [Wizcorp/container-avltree#1]
Hello
Thank you for this implementation!
You have typo:
```js
AvlTree.prototype._forEachReverse = function (node, processingFunc, params) {
	if (node !== null) {
		this._forEach(node.right, processingFunc, params);
		processingFunc(node.object, params);
		this._forEach(node.left, processingFunc, params);
	}
};
```
Should be `_forEachReverse` call

**Comment by bchevalier** [comment]
Hi,
Thanks for taking time to write an issue for it!

It should now be fixed.
Let me know if you have other issues, or if you think anything is missing API wise.
